channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=23.3.1
- pip:
  - mlflow==2.10.0
  - cloudpickle==3.0.0
  - numpy==1.26.3
  - packaging==23.2
  - pandas==2.2.0
  - pyyaml==6.0.1
  - torch==2.2.0
  - tqdm==4.66.1
name: mlflow-env
